### PR TITLE
Add Set-CrmSolutionVersionNumber function

### PR DESCRIPTION
**Pull request by ian-moore**
It's common to update the version number on a solution before exporting. Added a simple function to update the solution version.

### CODE REVIEW

**Comment by kenakamu** [comment]
Great idea! Could you consider throw error rather than write-error when something bad happens? And how about having validation for version number as you can pass any string for now?

**Comment by seanmcne** [comment]
Agreed, would be good to enforce a true version number as later versions to rely on using a real version "number".  You could regex the input value to verify.

**Comment by ian-moore** [comment]
I've made the suggested changes, is there anything else I should add?

**Comment by kenakamu** [comment]
Looks way better now :) Thanks! You can validate input at Parameter level.
https://msdn.microsoft.com/en-us/library/ms714454(v=vs.85).aspx
Once it's done let's merge this into main !

**Comment by ian-moore** [comment]
That was a good tip, I added that attribute to the version number parameter. It should validate version numbers that have between 2 and 4 parts.

**Comment by kenakamu** [comment]
Sorry for super late response but I merged it!!! this is great contribution :) Thanks a bunch!

**Pull request merged**
