### PR TITLE
Added Connect-CrmOnlineOAuth

### PR DESCRIPTION
**Pull request by RyanWAnderson**
Another constructor for CRM OL - using OAuth client id.

### CODE REVIEW

**Comment by seanmcne** [comment]
Thanks Ryan, 
I'm curious why you've added this?  CRM's SDK uses oAuth to connect to CRM Online today already, are you not seeing that?

**Comment by RyanWAnderson** [comment]
Hey Sean,

It's quite possible that I overlooked something, but I couldn't figure out how to connect as Support User (via ClientId and corpnet credentials).

I've got a class library that I am using in PS to do this, but other SEs would like to use this module.

Ping me if you can chat about it sometime.

Ryan (ryanande)


On Jan 4, 2017 13:33, Sean McNellis <notifications@github.com> wrote:

Thanks Ryan,
I'm curious why you've added this? CRM's SDK uses oAuth to connect to CRM Online today already, are you not seeing that?

**Comment by kenakamu** [comment]
OAuth is supported in CrmServiceClient so we don't need new commandlet, but adding new params to Connect-CrmOnline is better? Or do we want to have separate command?

**Comment by kenakamu** [comment]
Appreciate if you can comment on my last post.

**Comment by seanmcne** [comment]
@RyanWAnderson can you reach out to @kenakamu and I via email?  Let's discuss what you're seeing but I 100% agree on the use-case and can see why others would want to use it this way.

**Comment by RyanWAnderson** [comment]
I'm fine with another parameter set.

-Ryan



On Thu, Jan 26, 2017 at 5:01 PM -0600, "Sean McNellis" <notifications@github.com<mailto:notifications@github.com>> wrote:


@RyanWAnderson<https://github.com/RyanWAnderson> can you reach out to @kenakamu<https://github.com/kenakamu> and I via email? Let's discuss what you're seeing but I 100% agree on the use-case and can see why others would want to use it this way.

**Comment by seanmcne** [comment]
Will add clientid as an option soon - i've mocked something ryan if you want to try it out.

**Pull request closed without merging**
