### PR TITLE
Added capability to Import-CrmSolution with hold option, fixed false positive on Import-CrmSolution and added new capability to promote hold CRM solution upgrade

### PR DESCRIPTION
**Pull request by chamindac**
1. Added capability to Import-CrmSolution as hold solution
2. Fixed issue of giving false positive on Import-CrmSolution success when it fails without proper error thrown from CRM #114 
3. Apply Solution Upgrade capability added with DeleteAndPromote-CrmSolution this allows to upgrade a hold solution https://community.dynamics.com/crm/b/crminogic/archive/2016/01/25/solution-patching-in-microsoft-dynamics-crm-2016

### CODE REVIEW

**Comment by seanmcne** [comment]
Thanks can you also include a quick description of the new parameter and at least one example for the fix (so we can update the help), also would you be willing to write at least one example and documentation of each parameter for help purposes?  

Thanks!

**Comment by chamindac** [comment]
You are welcome! 

I have added some information below with the details of 
   1. New parameter
   2. Bug fix
   3. New Method to DeleteAndPromote-CrmSolution

Tried updating the help file in the solution but I could not get it to work properly, so I did not commit the help file changes.

I think below would be sufficient for you to update the help. Let me know if I should add more information to below.

************************************************************************************************
**Method - Import-CrmSolution**

*** New Parameter** - [parameter(Mandatory=$false, Position=5)]
        
		[switch]$ImportAsHoldingSolution

* Description - Specify the parameter to import Managed CRM Solution as a holding solution. To promote the managed solution and appy the upgrade you can use DeleteAndPromote-CrmSolution. This parameter is mutually exclusive with <OverwriteUnManagedCustomizations>. version number of the CRM managed solution importing must be increased to make holding import to be successful.

**Example**
------------------------------------------------------------------------------------------------
Import-CrmSolution -conn $conn -SolutionFilePath "C:\SampleSolution_1_0_0_1.zip" -MaxWaitTimeInSeconds 3600 -ImportAsHoldingSolution


************************************************************************************************
**Method - Import-CrmSolution**

*** Bug fix** - The solution import was giving false positive, at times when the solution import reveres and result does not contain error situations. Used job processing % to detect the revering of import job and if revered considered as a failure.

In a scenario where a solution is failing it will start reversing the import as shown below. The change to code will detect that and prevent the job % being set to 100% to avoid showing false positive. example failure scenario below, with TFS release services trying to deploy a CRM solution sing the module.


_2016-06-22T03:07:46.8305449Z 557 seconds of max: 3600 ... ImportJob%: 69.3 
2016-06-22T03:07:52.0180106Z 562 seconds of max: 3600 ... ImportJob%: 69.72 
2016-06-22T03:07:57.1117294Z 567 seconds of max: 3600 ... ImportJob%: 70.07
2016-06-22T03:08:02.2991939Z VERBOSE: Processing is reversing... import will fail. 
2016-06-22T03:08:02.2991939Z 572 seconds of max: 3600 ... ImportJob%: 68.94 
2016-06-22T03:08:07.4241659Z VERBOSE: Processing is reversing... import will fail. 
2016-06-22T03:08:07.4241659Z 577 seconds of max: 3600 ... ImportJob%: 68.94 
2016-06-22T03:08:12.5803870Z VERBOSE: Processing is reversing... import will fail. 
2016-06-22T03:08:12.5803870Z 583 seconds of max: 3600 ... ImportJob%: 68.94 
2016-06-22T03:08:17.6897216Z VERBOSE: Processing is reversing... import will fail. 
2016-06-22T03:08:17.6897216Z 588 seconds of max: 3600 ... ImportJob%: 68.59 
2016-06-22T03:08:22.8615632Z VERBOSE: Processing is reversing... import will fail. 
2016-06-22T03:08:22.8615632Z 593 seconds of max: 3600 ... ImportJob%: 26.57 
2016-06-22T03:08:27.9552856Z VERBOSE: Processing is reversing... import will fail. 
2016-06-22T03:08:27.9552856Z 598 seconds of max: 3600 ... ImportJob%: 6.14
 
2016-06-22T03:08:38.7833443Z VERBOSE: Processing Completed at: 6/21/2016 11:08 PM with ImportJob%: 70.35 
2016-06-22T03:08:39.1739590Z ##[error]Import-CrmSolution : System.Management.Automation.RuntimeException: Import result: Job with ID:  
2016-06-22T03:08:39.1739590Z ##[error]d77a8949-4f04-432f-bea1-610ac283302f failed at 70.35 percent complete. 
2016-06-22T03:08:39.1739590Z ##[error]At C:\r\w\78a092612\Prdct.M.Rel\drop\Pkg\CRM\DeployScripts\DeployCRMSolutions.ps1:71 char:13 
2016-06-22T03:08:39.1739590Z ##[error]+             Import-CrmSolution -conn $crmcon -SolutionFilePath $SolutionZipFileP ... 
2016-06-22T03:08:39.1739590Z ##[error]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
2016-06-22T03:08:39.1739590Z ##[error]    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
2016-06-22T03:08:39.1739590Z ##[error]    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-CrmSolution 
2016-06-22T03:08:39.1739590Z ##[error]  
2016-06-22T03:08:39.1739590Z ##[error]Process completed with exit code 1 and had 1 error(s) written to the error stream._




************************************************************************************************

**Method - DeleteAndPromote-CrmSolution**

Description - A solution imported as a holding solution, using Import-CrmSolution with -ImportAsHoldingSolution parameter, should be available to execute this method. This method will delete the old version and all patches of the specified solution, while keeping the data of the entities. It will apply the new version of the solution to CRM. This is similar to clicking on Apply Solution Upgrade after importing a solution as a hoding solution in CRM solution import in UI.

------------------------------------------------------------------------------------------------
**Parameters**

	[parameter(Mandatory=$false)]
        
	[Microsoft.Xrm.Tooling.Connector.CrmServiceClient]$conn
        
	
	Description - A connection to your CRM organization. Use $conn = Get-CrmConnection <Parameters> to generate it
	------------------------------------------------------------------------------------------------
	[parameter(Mandatory=$false, Position=1)]
        
	[string]$SolutionName
        
	
	Description - Managed CRM olution name that should be replaced, with the new version already imported as a holding solution using Import-CrmSolution with -ImportAsHoldingSolution parameter.
	------------------------------------------------------------------------------------------------
	[parameter(Mandatory=$false, Position=2)]
        
	[int64]$MaxWaitTimeInSeconds = 900
	
	Description - Wait time to wait for Apply Upgrade Solution synchronous opration to complete. Default is 900 seconds.
	------------------------------------------------------------------------------------------------

**Example**
------------------------------------------------------------------------------------------------
DeleteAndPromote-CrmSolution -conn $conn -SolutionName "SampleSolution" -MaxWaitTimeInSeconds 1200

**Comment by seanmcne** [comment]
@chamindac, I thought I could change the target of your commit but it looks like I'll have to have you edit it - can you change the target to the "Import-SolutionFix_Community" branch?  This should allow us to test it and edit / verify before publishing into master - thx (and sorry for the extra step).

**Comment by chamindac** [comment]
@seanmcne Sure I will close this request and add a new one.

**Pull request closed without merging**
