### PR TITLE
Fix for issue #153

### PR DESCRIPTION
**Pull request by thuld**
Introduces the new function "Get-FieldTypeByFieldValue". This function
is responsible to map the value of a field to the corresponding CRM-Data-Type.

### CODE REVIEW

**Comment by kenakamu** [comment]
Thanks for this @thuld, this is great :)

There are several things I request you to update.

1. As this is going to be an internal function, could you change the function name without verb so that we can avoid exposing it.
2. Please use change the last line of added function to return $type rather than $type; (line 242)
3. I avoid using ";" as line terminator. Please remove them all to match the formatting.

**Comment by thuld** [comment]
I have update the code as requested and committed those changes. 

Daniel

**Comment by kenakamu** [comment]
Could you do return $crmDatatype and delete all ";" for private function too?

**Comment by thuld** [comment]
Changed to ````return $crmDatatype````. 

Not sure what you mean by "and delete all ";" for private function too" are you talking about the ";" in the hashtable:

`$valueTypeToCrmTypeMapping = @{
        "Boolean" = [Microsoft.Xrm.Tooling.Connector.CrmFieldType]::CrmBoolean
        "DateTime" = [Microsoft.Xrm.Tooling.Connector.CrmFieldType]::CrmDateTime
        "Decimal" = [Microsoft.Xrm.Tooling.Connector.CrmFieldType]::CrmDecimal
        "Single" = [Microsoft.Xrm.Tooling.Connector.CrmFieldType]::CrmFloat
        "Money" = [Microsoft.Xrm.Tooling.Connector.CrmFieldType]::Raw
        "Int32" = [Microsoft.Xrm.Tooling.Connector.CrmFieldType]::CrmNumber
        "EntityReference" = [Microsoft.Xrm.Tooling.Connector.CrmFieldType]::Raw
        "OptionSetValue" = [Microsoft.Xrm.Tooling.Connector.CrmFieldType]::Raw
        "String" = [Microsoft.Xrm.Tooling.Connector.CrmFieldType]::String
        "Guid" =  [Microsoft.Xrm.Tooling.Connector.CrmFieldType]::UniqueIdentifier
    }`

**Comment by kenakamu** [comment]
my bad. please ignore the ";" for hashtable.

**Pull request merged**
