### PR TITLE
Issue #185

### PR DESCRIPTION
**Pull request by RIKIKU**
Added the additional fields as requested.  
@seanmcne  Did you want the testemailconfigurationscheduled  property to be a bool? Other properties like this one are just Yes/No Strings.

### CODE REVIEW

**Comment by seanmcne** [comment]
You should be able to just leave that whole part out - the function executing the fetch should return the property as-is - we do not want it to be a string (it should match the original type).

**Comment by RIKIKU** [comment]
I've removed the part that converts it to a bool. That property is returned from the server as a string data type and has a value of either Yes or No.

**Comment by seanmcne** [comment]
@RIKIKU 
First off, thanks for your contribution here and I want to apologize for the delay on our part.  I spent a little time looking at this function today and honestly I'm not sure why we've got the additional handling of properties in here - I suspect it was something legacy introduced prior to consolidating other functions. 

Here's what I'd propose (feel free to do this or you can punt it back to me and @kenakamu - whatever you want) : 
1. Let's keep the updated fetch so that it includes: 
``` xml
<attribute name="regardingobjectid" /> 
<attribute name="testemailconfigurationscheduled" />
```

2. remove everything else, I don't see any reason for us to do what we were doing before - we should just return the mailbox record as-is (IMO) - the helper can be reduced down to some basic checking: 

```powershell
	$mailboxes = (Get-CrmRecordsByFetch -conn $conn -Fetch $fetch).CrmRecords
	if($mailboxes.Count -gt 1){
		throw "More than 1 mailbox found for user: $UserId"
	}
	elseif($mailboxes.Count -eq 0){
		throw "User with ID: $UserId does not have an associated mailbox."
	}
	return $record;
```

**Comment by RIKIKU** [comment]
Hi @seanmcne , no worries with the delay. The way I see it, GitHub is essentially a volunteer service so, I understand that we all have lives outside of this. 

 I'll take a look at this, Update the fetch and improve error checking where I can.  I'm not really sure if adding that $name attribute is good or bad as it may confuse a user into thinking that Name is the attribute name or something.. On the other hand, the output of this cmdlet could be used as pipeline input and Name just makes it work on more things.. I'll let ya know what I find.

**Comment by RIKIKU** [comment]
Hey @seanmcne , 
I just had a thought, why don't we just use <all-attributes /> in the fetch? That way we aren't making any assumptions about what kind of data is useful to the user and if attributes are added or removed in the future, we won't have to update the fetch.  

I can see what you mean about that stuff in the helper now. I agree we should remove it. I think the motivation behind it might have been to make an object that was easier to read, however doing so has the downside that the object is less useful overall. Perhaps if we need to cut down the data that is returned to the user, we could look at custom format views for the answer. That way only superficial changes to the output are made, but the data structure would be the same underneath.

**Comment by seanmcne** [comment]
Looks good - one thing I'm a little concerned with though is the custom typing, I know this will be helpful in formatting but we've talked about doing this more generically for 'entities' (maybe) but don't want to back ourselves into a corner with a custom Type that we might have to get rid of or handle differently.  If you could pull that out for now (sorry) we can kick around the idea a bit more.  Thanks again for all the hard work and back and forth on this!

**Comment by RIKIKU** [comment]
Yeah, not a problem. I just threw them in there because the output was a bit verbose after I added the all-attributes node. I also had a format file kicking around from another project, so it was easy.

**Pull request merged**
