### PR TITLE
Adding missing connection parameters on some internal calls

### LINKED ISSUE #474: Explicitly passed connection sometimes not respected
`Get-CrmSystemSettings` fails to retrieve the system settings if a connection is explicitly passed via `-conn`, and either grabs data from the ambient globally scoped `$conn` (i.e. the wrong behaviour) or outright fails if there is no global `$conn`.

I've identified the problem as the various calls to `Get-CrmEntityOptionSet` not specifying the `-conn` parameter and thus using the fallback logic.

I've also gone through and checked the rest of the module for similar issues, and `Invoke-CrmRecordWorkflow` has the same issue calling `Get-CrmRecordsByFetch`.

### PR DESCRIPTION
**Pull request by matwilko**
Fixes #474

### CODE REVIEW

**Comment by seanmcne** [comment]
Wow this is great, thanks for adding this!  Have you tested, after these changes, connecting without explicitly passing a connection?   is it still working by finding the global $conn object/connection?

**Comment by matwilko** [comment]
Honestly, I haven't tested for that case - but given that in both functions the `$conn` being passed down is already verified at the start of the function with `$conn = VerifyCrmConnectionParam -conn $conn -pipelineValue ($PSBoundParameters.ContainsKey('conn'))`, which should pick up the global `$conn` if it needs to, I _assume_ it should work.

I can go and explicitly test if you wish?

**Comment by seanmcne** [comment]
If you have it locally setup & could try it, that would be great.  I also think it's going to be fine as the helper function should detect a null object and find the global one - but it usually never hurts to test :)

**Comment by matwilko** [comment]
I've tested `Get-CrmSystemSettings` works in both cases (explicitly passed connection, implicit global `$conn`).

I have no idea how to test `Invoke-CrmRecordWorkflow`, I'm definitely no dynamics expert, so I don't know how to set up the required resources to do so (I initially ran into this problem in `Get-CrmSystemSettings` and just expanded to find any other examples)

If you're satisfied both will work from one of them working, cool, otherwise I can rebase out the change to `Invoke-CrmRecordWorkflow` so that an untested change doesn't make it into the shipping module? (or if you have a way to poke at `Invoke-CrmRecordWorkflow`, all the better)

**Pull request merged**
