### PR TITLE
add client secret connection method 

### PR DESCRIPTION
**Pull request by seanmcne**
Bump version #
Add ClientSecret auth to connect-crmonline

### CODE REVIEW

**Comment by aaronhamilton** [comment]
Hi Sean. Do you have an example of using the ClientSecret method? I have the latest version of Microsoft.Xrm.Data.Powershell (2.8.12) but I don't see any way to add ClientSecret as credential and it doesn't appear in the help. Thanks!

**Comment by seanmcne** [comment]
Hi Aaron try 
'''
Get-Help Connect-CrmOnline -Examples 
'''

Example # 4 should show this - I'm not at a PC today but let me know you still aren't seeing it.

**Comment by aaronhamilton** [comment]
Hey Sean

I see only two examples

Perplexed in Toronto
Aa

**Comment by seanmcne** [comment]
Might want to consider re-installing the module - it's strange the help isn't showing all the examples. If you continue to have an issue w/ this please open a new issue under the issues tab and we can work through it - thanks! 

Here is how you connect with a client secret: 
```
#verbose isn't required but will show you what's going on to construct the connection string 
Connect-CrmOnline -ServerUrl "https://contoso.crm.dynamics.com" -ClientSecret "T_DA0EY+DdfaJFH3/DFLK@QoFbY" -OAuthClientId "812fad6d-4727-44f5-b02e-f35d74efb78e" -verbose
```
Once you run the command (so it's loaded) you can check the version loaded by running a get-module: 
image

For reference, here is the output from the following command: get-help Connect-CrmOnline -Examples
```
NAME
    Connect-CrmOnline
    
SYNOPSIS
    Connects to CRM Online organization without using Discovery Service.
    
    
    --------------------------  Example 1 Office365 legacy authentication  --------------------------
    
    PS C:\> Connect-CrmOnline -Credential (Get-Credential) -ServerUrl "https://contoso.crm.dynamics.com"
    
    Connect to online using your organization URL
    
    
    
    IsReady                        : True
    IsBatchOperationsAvailable     : True
    Authority                      :
    OAuthUserId                    :
    ActiveAuthenticationType       : Office365
    OrganizationServiceProxy       : Microsoft.Xrm.Tooling.Connector.CrmWebSvc+ManagedTokenOrganizationServiceProxy
    OrganizationWebProxyClient     :
    LastCrmError                   : OrganizationWebProxyClient is null
    LastCrmException               :
     CrmConnectOrgUriActual         : https://contoso.api.crm.dynamics.com/XRMServices/2011/Organization.svc
     ConnectedOrgFriendlyName       : contoso
     ConnectedOrgUniqueName         : contoso
     ConnectedOrgPublishedEndpoints : {[WebApplication, https://contoso.crm.dynamics.com/], [OrganizationService, 
                                      https://contoso.api.crm.dynamics.com/XRMServices/2011/Organization.svc], 
                                      [OrganizationDataService, 
                                      https://contoso.api.crm.dynamics.com/XRMServices/2011/OrganizationData.svc]}
    ConnectionLockObject           : System.Object
    ConnectedOrgVersion            : 9.1.0000.0000
    DisableCrossThreadSafeties     : False
    CallerId                       : 00000000-0000-0000-0000-000000000000
    
    --------------------------  Example 2 oAuth Single Sign on  --------------------------
    
    PS C:\> Connect-CrmOnline -ServerUrl "https://contoso.crm.dynamics.com" -ForceOAuth
    
    Connect to online using your organization URL using oAuth attempting single sign on - sign on using ADAL and the 
    browser is attempted when a credential is not provided.
    
    
    
    IsReady                        : True
    IsBatchOperationsAvailable     : True
    Authority                      : https://login.windows.net/{guid}/oauth2/authorize/
    OAuthUserId                    : user@contoso.com 
    ActiveAuthenticationType       : OAuth
    OrganizationServiceProxy       :
    OrganizationWebProxyClient     : Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClient
    LastCrmError                   :
    LastCrmException               :
    CrmConnectOrgUriActual         : 
    https://contoso.api.crm.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.0.9002.0
    ConnectedOrgFriendlyName       : Contoso
    ConnectedOrgUniqueName         : contosocrmol
    ConnectedOrgPublishedEndpoints : {[WebApplication, https://contoso.crm.dynamics.com/], [OrganizationService, 
    https://contoso.api.crm.dynamics.com/XRMServices/2011/Organization.svc], [OrganizationDataService, 
    https://contoso.api.crm.dynamics.com/XRMServices/2011/OrganizationData.svc]}
    ConnectionLockObject           : System.Object
    ConnectedOrgVersion            : 9.1.0000.0000
    DisableCrossThreadSafeties     : False
    CallerId                       : 00000000-0000-0000-0000-000000000000
    
    --------------------------  Example 3 oAuth with credenital  --------------------------
    
    PS C:\> Connect-CrmOnline -ServerUrl "https://contoso.crm.dynamics.com"  -Credential (Get-Credential) -ForceOAuth
    
    Connect to online using your organization URL using oAuth using provided credential.
    
    
    
    IsReady                        : True
    IsBatchOperationsAvailable     : True
    Authority                      : https://login.windows.net/{guid}/oauth2/authorize/
    OAuthUserId                    : user@contoso.com 
    ActiveAuthenticationType       : OAuth
    OrganizationServiceProxy       :
    OrganizationWebProxyClient     : Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClient
    LastCrmError                   :
    LastCrmException               :
    CrmConnectOrgUriActual         : 
    https://contoso.api.crm.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.0.9002.0
    ConnectedOrgFriendlyName       : Contoso
    ConnectedOrgUniqueName         : contosocrmol
    ConnectedOrgPublishedEndpoints : {[WebApplication, https://contoso.crm.dynamics.com/], [OrganizationService, 
    https://contoso.api.crm.dynamics.com/XRMServices/2011/Organization.svc], [OrganizationDataService, 
    https://contoso.api.crm.dynamics.com/XRMServices/2011/OrganizationData.svc]}
    ConnectionLockObject           : System.Object
    ConnectedOrgVersion            : 9.1.0000.0000
    DisableCrossThreadSafeties     : False
    CallerId                       : 00000000-0000-0000-0000-000000000000
    
    --------------------------  Example 4 oAuth with ClientSecret  --------------------------
    
    PS C:\> Connect-CrmOnline -ServerUrl "https://contoso.crm.dynamics.com" -ClientSecret 
    "T_DA0EY+DdfaJFH3/DFLK@QoFbY" -OAuthClientId "812fad6d-4727-44f5-b02e-f35d74efb78e" -OAuthRedirectUri 
    "https://tempuri.org"
    
    Connect to a CDS instance as an application user, using ClientSecret authentication
    
    
    
    MaxRetryCount                       : 10
    RetryPauseTime                      : 00:00:05
    IsReady                             : True
    IsBatchOperationsAvailable          : True
    Authority                           : https://login.microsoftonline.com/{guid}/oauth2/authorize/
    OAuthUserId                         :
    ActiveAuthenticationType            : ClientSecret
    OrganizationServiceProxy            :
    OrganizationWebProxyClient          : Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClient
    LastCrmError                        :
    LastCrmException                    :
    CrmConnectOrgUriActual              : 
    https://contoso.crm.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientV
                                          ersion=9.1.0000.0000
    ConnectedOrgFriendlyName            : [9.1] contoso seanmcn
    ConnectedOrgUniqueName              : contoso
    ConnectedOrgPublishedEndpoints      : {[WebApplication, https://contoso.crm.dynamics.com/], [OrganizationService,
                                          https://contoso.api.crm.dynamics.com/XRMServices/2011/Organization.svc],
                                          [OrganizationDataService,
                                          https://contoso.api.crm.dynamics.com/XRMServices/2011/OrganizationData.svc]}
    ConnectionLockObject                : System.Object
    ConnectedOrgVersion                 : 9.1.0000.0000
    ConnectedOrgId                      : b283ca00-d54d-4dd0-ba1a-ee8e51d5256a
    DisableCrossThreadSafeties          : False
    CallerId                            : 00000000-0000-0000-0000-000000000000
    CallerAADObjectId                   :
    SessionTrackingId                   :
    ForceServerMetadataCacheConsistency : False
    SdkVersionProperty                  : 9.1.0000.0000
    TenantId                            : 03cd4258-2030-45a3-aea9-508adbed80b6
    EnvironmentId                       : 11537934-8ab9-4721-aba1-0feff3133e38
    _sdkVersionProperty                 : 9.1.0000.0000
    
    --------------------------  Example 5 ConnectionString FOR DEBUGGING  --------------------------
    
    PS C:\> Connect-CrmOnline -ConnectionString "RequireNewInstance=True;Url=https://naosrtw.crm.dynamics.com;AuthType=
    ClientSecret;ClientId=812fad6d-4727-44f5-b02e-f35d74efb78e;SkipDiscovery=True;ClientSecret=T_DA0EY+DdfaJFH3/DFLK@Qo
    FbY" -ConnectionTimeoutInSeconds 500 -LogWriteDirectory "C:\temp\"
    
    Connect to a CDS instance as an application user, using a custom connectionstring
    
    Use with caution and *only* for debugging as this may change or parameter may be removed in the future.
```

**Comment by aaronhamilton** [comment]
Hi Sean

Thanks for the guidance! I tried a couple of things...
1. switched farms and discovered Get-Help is showing all 5 examples in my Prod farm!
2. opened a fresh PowerShell ISE on Dev and it's showing all 5 examples. 

I suspect that my forced Update last week didn't refresh the cached objects in ISE

I have now successfully connected to D365 using ClientID/AppID and ClientSecret!  

Thanks so much for pointing me in the right direction Sean! 

P.S. I do have another question related to Connect-CrmOnline and data migrations--should I open another issue for that, or do you have an alternative preference...?

**Pull request merged**
