### PR TITLE
Added the additional All location filter param value for Get-CrmEntit…

### PR DESCRIPTION
**Pull request by mhuguet**
…yRibbonXml as the default was not returning all of the detail.

### CODE REVIEW

**Comment by seanmcne** [comment]
@mhuguet can you make the $conn param optional?  The verify connection will check the global variable first and if it doesn't exist throw back an exception asking for the connection parameter (as it can either be passed or assumed based on the user already connecting). 

Example: 
[parameter(Mandatory=$false)] 
[Microsoft.Xrm.Tooling.Connector.CrmServiceClient]$conn,

**Comment by mhuguet** [comment]
Is it not already set to $false?  I looked and both were set that way locally.

Date: Fri, 12 Feb 2016 05:24:54 -0800

**Comment by kenakamu** [comment]
You added two functions but Export-CrmEntityRibbonXml merely save definition to disk. If the purpose of this function is to save it to local, then we may not need Get-CrmEntityRibbonXml? Do we have any usage of Get-CrmEntityRibbonXml by itself, otherwise I will merge them together and keep Export-CrmEntityRibbonXml only, In addition I will add Application Ribbon too to have complete capabilities

**Comment by seanmcne** [comment]
+ @mhuguet - Mike, thoughts?  App ribbon could just be a param @kenakamu or offer up an override as I think it's just a slightly different entity name value.

**Pull request merged**
